package cn.lnfvc.ken.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import cn.lnfvc.ken.service.OrderService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-10-17T10:50:10.317+08:00
 * Generated source version: 3.4.0
 *
 */
@WebServiceClient(name = "OrderServiceImplService",
                  wsdlLocation = "http://127.0.0.1:8001/webService/orderService/demo?wsdl",
                  targetNamespace = "http://impl.service.ken.lnfvc.cn/")
public class OrderServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.ken.lnfvc.cn/", "OrderServiceImplService");
    public final static QName OrderServiceImplPort = new QName("http://impl.service.ken.lnfvc.cn/", "OrderServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8001/webService/orderService/demo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8001/webService/orderService/demo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OrderServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OrderServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OrderServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "OrderServiceImplPort")
    public OrderService getOrderServiceImplPort() {
        return super.getPort(OrderServiceImplPort, OrderService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "OrderServiceImplPort")
    public OrderService getOrderServiceImplPort(WebServiceFeature... features) {
        return super.getPort(OrderServiceImplPort, OrderService.class, features);
    }

}
