package cn.lnfvc.ken.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-10-17T10:50:10.282+08:00
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "http://service.ken.lnfvc.cn/", name = "OrderService")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderService {

    @WebMethod
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.ken.lnfvc.cn/", className = "cn.lnfvc.ken.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.ken.lnfvc.cn/", className = "cn.lnfvc.ken.service.FindAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<cn.lnfvc.ken.service.Order> findAll()
;

    @WebMethod
    @RequestWrapper(localName = "create", targetNamespace = "http://service.ken.lnfvc.cn/", className = "cn.lnfvc.ken.service.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://service.ken.lnfvc.cn/", className = "cn.lnfvc.ken.service.CreateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int create(

        @WebParam(name = "arg0", targetNamespace = "")
        cn.lnfvc.ken.service.Order arg0
    );
}
